### ISSUE TITLE
Array of sampler uniforms not translated correctly to Metal

### ISSUE THREAD

**Issue by eodabash** [aras-p/glsl-optimizer#106]
It seems that GLSL shaders with uniform sampler arrays such as:

`uniform sampler2D mySamplers[2];`

do not get translated properly to Metal, the resulting output is trying to sample from them with code like this:

`_mtl_u.mySamplers[0].sample(_mtlsmp__mtl_u.mySamplers[0], (float2)(_mtl_i.texCoord))`

but the `_mtlsmp__mtl_u` type is not declared anywhere. 

Full test shader here: https://gist.github.com/eodabash/bdaf2341f49d504b19e9.

**Comment by floooh** [comment]
Yes, currently uniform arrays are not supported at all in the shader code generator. It my be that they work by accident in GLSL. I'll rename this ticket to track the implementation of uniform arrays.

**Comment by floooh** [comment]
Ooops nevermind, wrong project ;)

**Comment by eodabash** [comment]
I see in the Metal spec that arrays of samplers/textures are not even supported, so I'll just close this I guess.
