### ISSUE TITLE
switch statements not functioning?

### ISSUE THREAD

**Issue by mbechard** [aras-p/glsl-optimizer#124]
It seems like switch statements don't work, which are supported in GLSL 1.3+.
I think part of the issue is the MESA code which isn't outputting correct instructions, For example `_mesa_print_ir()` outputs instructions like this:

```
(assign (expression bool all_equal (constant int (0)) (var_ref compiler_temp@4) )  (x) (var_ref compiler_temp)  (constant bool (1)) )

(assign (var_ref compiler_temp@2)  (x) (var_ref compiler_temp)  (constant bool (0)) )
```

Which `_mesa_print_ir_glsl()` turns into something like:

```
(0 == b1) tmpvar_1 = bool(1);
tmpvar_2 tmpvar_1 = bool(0);
```

Which of course is invalid code. Any plans to upgrade to the latest MESA? I'm interested in trying to add GLSL 3.30 support to this project.

Thanks

E.g

```
#version 130
uniform int b1;

void main()
{
    switch (b1)
    {
        case 0:
            gl_FragColor = vec4(1.0);
            break;
        case 1:
            gl_FragColor = vec4(1.0);
            break;
    }
}
```

Creates:

```
#version 130
uniform int b1;
void main ()
{
  bool tmpvar_1;
  tmpvar_1 = bool(0);
  bool tmpvar_2;
  tmpvar_2 = bool(0);
  (0 == b1) tmpvar_1 = bool(1);
  tmpvar_2 tmpvar_1 = bool(0);
  if (tmpvar_1) {
    gl_FragColor = vec4(1.0, 1.0, 1.0, 1.0);
    tmpvar_2 = bool(1);
  };
  (1 == b1) tmpvar_1 = bool(1);
  tmpvar_2 tmpvar_1 = bool(0);
  if (tmpvar_1) {
    gl_FragColor = vec4(1.0, 1.0, 1.0, 1.0);
    tmpvar_2 = bool(1);
  };
}
```

**Comment by passerbythesun** [comment]
I meet this problem, too. But I just don't understand the syntax ...

**Comment by jrmuizel** [comment]
I ran into this and fixed it locally with: https://github.com/jrmuizel/glsl-optimizer/commit/6df8af46ee4615dcca32e1a9d15cec11f6837ca8
