### ISSUE TITLE
required preprocessor conditionals are optimized out.

### ISSUE THREAD

**Issue by mchiasson** [aras-p/glsl-optimizer#139]
I have the following at the top of my GLSL ES shader for GLES 2.0 platform:

```
    #if defined(GL_OES_standard_derivatives)
        #extension GL_OES_standard_derivatives : enable
    #endif
    precision highp float;
    ...
```
And uses this extension as such:
```
...
float calculateSmoothing(in float distance)
{
#if defined(GL_OES_standard_derivatives)
    return (0.707106781 * length(vec2(dFdx(distance), dFdy(distance))));
#else
    return u_smoothing / gl_FragCoord.w;
#endif
}
...
``` 

And after it was optimised, it turned to this:
```
#extension GL_OES_standard_derivatives : enable
precision highp float;
```
while `calculateSmoothing` turned into the following in my main (got inlined, which is awesome):
```
...
lowp float tmpvar_4;
lowp vec2 tmpvar_5;
tmpvar_5.x = dFdx(tmpvar_3);
tmpvar_5.y = dFdy(tmpvar_3);
tmpvar_4 = (0.7071068 * sqrt(dot (tmpvar_5, tmpvar_5)));
...
```
and the `u_smoothing` was optimised out.

The GLSL optimizer works great. My mind is blown away. However, there's one major problem:  my shader doesn't work anymore on hardware that doesn't support the `GL_OES_standard_derivatives` extension (e.g. RaspberryPi, Amazon FireTV Stick gen 1, etc)

Is there a way to keep the preprocessor conditionals as-is? or perhaps there's a way to generate 2 optimised versions of my shader (one version with the extension, the other without the extension)?

Any help would be greatly appreciated! Thanks!

**Comment by aras-p** [comment]
Yeah so the problem is that GLSL optimizer works by fully parsing the shader (which includes doing the full preprocessing), optimizing the resulting IR, and "printing" it back to GLSL (or Metal).

So yes cases like that will be "optimized out".

I guess you could generate two versions of your shader, by doing optimization of:
1) your original shader (which will work as if `GL_OES_standard_derivatives ` is defined),
2) same shader of yours, with `#undef GL_OES_standard_derivatives` prepended in front of the shader text.

Or something like that.

**Comment by mchiasson** [comment]
Prepending `#undef GL_OES_standard_derivatives` at the top of the file works! (can't believe I didn't think of that!)

Thank you @aras-p! glsl-optimizer is amazing! Keep up the good work!

**Comment by mchiasson** [comment]
Problem solved. Closing.

**Comment by aras-p** [comment]
Yay!

Though frankly I'm not sure how useful glsl-optimizer is in 2017. Back in 2010, the main reason was the mobile OpenGL drivers were extremely weak at doing shader optimizations. I would hope that seven years later almost all drivers have some sort of LLVM-based compilers underneath, with pretty good optimizations?

**Comment by bkaradzic** [comment]
It's quite useful to do offline compilation, strip dead code, etc.
