### ISSUE TITLE
disable optimization for expression/line

### ISSUE THREAD

**Issue by crazii** [aras-p/glsl-optimizer#145]
Is it possible to and a hint ( pragma or something) to disable the optimization for one single expression?

i.e. Currently I encounter a dot(vec4, vec4) bug on Adreno, and when I explicitly use l.x*r.x + l.y*r.y + l.z*r.z + l.w*r.w, the optimizer always optmize it to a dot(), so if it will be much better if I can disable optimization for a specific expression.

**Comment by aras-p** [comment]
No, that does not exist :(
