### ISSUE TITLE
Add support for GameMaker Studio constants

### ISSUE THREAD

**Issue by m1s3ry** [aras-p/glsl-optimizer#152]
It should be relatively easy, as there are few of them only. 
https://gmshaders.com/glossary/ (bottom part)

**Comment by m1s3ry** [comment]
```
uniform sampler2D gm_BaseTexture;

uniform bool gm_PS_FogEnabled;
uniform vec4 gm_FogColour;
uniform bool gm_AlphaTestEnabled;
uniform float gm_AlphaRefValue;
```

**Comment by aras-p** [comment]
I'm not sure what is the request or why. Glsl Optimizer just takes an input GLSL shader, and writes an output GLSL (or Metal) shader. If your shader has a thing like `uniform sampler2D gm_BaseTexture` in there, then it's there. What special treatment they should get that does not work today?
