### ISSUE TITLE
Build on Linux+CMake is broken

### ISSUE THREAD

**Issue by ColinGilbert** [aras-p/glsl-optimizer#85]
Hi,

Here is the error I receive at the very beginning:

```
In file included from src/glsl/glcpp/glcpp-parse.y:31:0:
/home/noob/CoolCode/glsl-optimizer/src/glsl/glcpp/glcpp.h:32:25: fatal error: util/ralloc.h: No such file or directory
 #include "util/ralloc.h"
                         ^
compilation terminated.
CMakeFiles/glcpp-library.dir/build.make:54: recipe for target 'CMakeFiles/glcpp-library.dir/src/glsl/glcpp/glcpp-parse.c.o' failed
make[2]: *** [CMakeFiles/glcpp-library.dir/src/glsl/glcpp/glcpp-parse.c.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/glcpp-library.dir/all' failed
make[1]: *** [CMakeFiles/glcpp-library.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
```
Tried with CMake in both a separate build directory, and an in-source build; neither worked. Running Gentoo.

**Comment by aras-p** [comment]
Like written in readme :) "Note: only the VS and Xcode project files are maintained and should work at any time. There's also a cmake and gyp build system for Linux et al., and some stuff in contrib folder - all that may or might not work."

**Comment by ColinGilbert** [comment]
Oh :( Could you pretty-please bring it up to date? My own CMake-fu isn't very good; otherwise I'd gladly do it myself.

**Comment by aras-p** [comment]
I've no idea. I don't know how to use CMake, and I don't have Linux. All the Linux support and CMake/Makefile/gyp/... build systems were contributed by someone else :|

That said, just merged a patch from someone that supposedly fixes the regular Makefiles. Maybe try building with just that, instead of CMake?
