### ISSUE TITLE
segmentation fault in remove_unlinked_functions

### ISSUE THREAD

**Issue by ILOVEPIE** [aras-p/glsl-optimizer#89]
The remove_unlinked_functions function causes a segmentation fault.

**Comment by bkaradzic** [comment]
Which compiler, platform, etc?

If you're compiling with GCC does adding `-fno-strict-aliasing` fix it?

**Comment by ILOVEPIE** [comment]
let me check

**Comment by ILOVEPIE** [comment]
yes thank you that solved it.
